### ISSUE TITLE
Tag Processor - TagID not as expected - returns empty byte array - but throws no exception

### ISSUE THREAD

**Issue by chrisfabri** [aws-samples/amazon-chime-voiceconnector-transcription#45]
Hi - I've built a POC using the code given here:

https://github.com/aws-samples/amazon-chime-voiceconnector-transcription/tree/master/src/main/java/com/amazonaws/kvstranscribestreaming/transcribe 

this code  extracts bytes from Kinesis video stream and pushes these bytes to transcribe.

The code is failing silently when the tag processor detects that the transactionID for the KVM record that it is about to process is not the one it expects.  See line 32 here:

https://github.com/aws-samples/amazon-chime-voiceconnector-transcription/blob/master/src/main/java/com/amazonaws/kvstranscribestreaming/streaming/KVSTransactionIdTagProcessor.java 

When this condition occurs, byte processing stops - and the returned byte array is set to zero - see line
56 here:
https://github.com/aws-samples/amazon-chime-voiceconnector-transcription/blob/master/src/main/java/com/amazonaws/kvstranscribestreaming/utils/KVSUtils.java 

my question is: 

Q1 - when this occurs, can this be an error condition or is it always expected to occur at the end of a sequence of MKV records?

Tx.

Christopher

**Comment by danieludy** [comment]
The answer to that is it depends on how long after the call you retrieve the data from the KVS stream and how many calls you stream to KVS. 
The Voice Connector will reuse existing KVS streams over creating new ones if possible, so that transactionID check is there to verify that even if the same KVS stream is used for a subsequent call that you can differentiate where the frames for one call end and another begin.
 If you retrieve the media for a call and the same stream has not been used for a subsequent call then you will not see a new transactionID at the end

**Comment by chrisfabri** [comment]
k - thanks.
